language: java

env:
  global:
    - secure: "Uze8VFBIsg35ZR19/QmgCo7Sifo75TViTWePBeLdJh7sPO2WFFJVAPQIXNtD2kurCa3Qx4iyuxRucUI+eqJPqzTs8WfS8ocB4eSd+bwYa2UR9c98kCZGQwZI3B+PlYxd1d6TK3/uAhgH2OkaWp8KvSQMHw7/osSQ0Q6mqn3xOp4="
    - secure: "A0+qHoj7bdI8zjaKTqJGYrouWxjigdamDrDQqHuKDc9xcb9yUlT8oBmfLpum66LjcH1SZsj39aZgQc/8MuFKjzVBvvFUm79/pApr+43J4sPJSuFEJoJtcdPhHSxnRKvcIas4LY1XZjbxLf5SaKtFOaiLpoFkOXgyrxFUQwZAcE8="

script: "./gradlew build -x spotlessCheck"

jdk:
  - oraclejdk8
  
install: ./gradlew assemble --stacktrace -x spotlessCheck

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
after_success:
    - ./gradlew uploadArchives -x spotlessCheck -Plocal=true
